"""update relationship with order_by and orderinglist

Revision ID: 5eb226aaad4f
Revises: d572349cfc99
Create Date: 2023-02-22 16:29:45.078294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb226aaad4f'
down_revision = 'd572349cfc99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
