"""update role_id column

Revision ID: d572349cfc99
Revises: a582374ae16d
Create Date: 2023-02-21 18:41:20.045919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd572349cfc99'
down_revision = 'a582374ae16d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
